grafana:
  adminPassword: password!@#$
  ingress:
    enabled: true
    ingressClassName: traefik
    hosts:
      - grafana.local
  datasources:
    datasources.yaml:
      apiVersion: 1
      datasources:
      - name: Prometheus
        type: prometheus
        url: http://k8s-monitoring-prometheus-server.monitoring:80      
        isDefault: true
        editable: true
      - name: Mimir
        type: prometheus
        url: http://k8s-monitoring-mimir-nginx.monitoring.svc:80/prometheus
        editable: true
  dashboardProviders:
    dashboardproviders.yaml:
      apiVersion: 1
      providers:
      - name: 'default'
        orgId: 1
        folder: 'default'
        type: file
        disableDeletion: true
        editable: true
        options:
          path: /var/lib/grafana/dashboards/standard
  dashboards:
    default:
      k8s_global:
        gnetId: 15757
        revision: 1
        datasource: Mimir
      k8s_nodes:
        gnetId: 15759
        revision: 1
        datasource: Mimir  
      k8s_namespaces:
        gnetId: 15758
        revision: 1
        datasource: Mimir
      k8s_pods:
        gnetId: 15760
        revision: 1
        datasource: Mimir
prometheus:
  server:
    ingress:
      enabled: true
      ingressClassName: traefik
      hosts:
        - prometheus.local
    remoteWrite:
      - url: http://k8s-monitoring-mimir-nginx.monitoring.svc:80/api/v1/push
    global:
      external_labels:
        cluster: kw-local