grafana:
  adminPassword: password!@#$
  ingress:
    enabled: true
    ingressClassName: traefik
    hosts:
      - grafana.local

  datasources:
    datasources.yaml:
      apiVersion: 1
      datasources:
      - name: Prometheus
        type: prometheus
        url: http://k8s-monitoring-prometheus-server.monitoring:80      
        isDefault: true
        editable: true
      - name: Mimir
        type: prometheus
        url: http://k8s-monitoring-mimir-nginx.monitoring.svc:80/prometheus
        editable: true

prometheus:
  server:
    ingress:
      enabled: true
      ingressClassName: traefik
      hosts:
        - prometheus.local
    remoteWrite:
      - url: http://k8s-monitoring-mimir-nginx.monitoring.svc:80/api/v1/push